package org.bolmitra.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowLeft
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowRight
import androidx.compose.material.icons.automirrored.filled.List
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import android.graphics.Bitmap
import androidx.compose.foundation.Image
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.graphics.asImageBitmap
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.bolmitra.curriculum.AssemblyResult
import org.bolmitra.curriculum.GeneratedItem
import org.bolmitra.curriculum.NumeracySeed
import org.bolmitra.curriculum.QrCode
import org.bolmitra.curriculum.WorksheetAssembler
import org.bolmitra.speech.TargetLanguage
import org.bolmitra.ui.common.AppNotice
import org.bolmitra.ui.common.NoticeKind
import org.bolmitra.ui.common.NotificationHost
import org.bolmitra.ui.common.WorksheetPreviewSheet
import org.bolmitra.ui.common.WorksheetThumbnail
import org.bolmitra.ui.common.rememberNotifier

data class WorksheetItem(
    val title: String,
    val subtitle: String,
    val gradePages: String,
    val categoryIndex: Int,
)

/**
 * Worksheets Screen — Exact replica of Image 3.
 */
@Composable
fun WorksheetsScreenPane(
    wide: Boolean,
    modifier: Modifier = Modifier,
) {
    var selectedLang by remember { mutableStateOf(TargetLanguage.MUNDARI) }
    var searchQuery by remember { mutableStateOf("") }
    var selectedCategory by remember { mutableStateOf(0) } // 0: All
    var selectedWorksheetIndex by remember { mutableStateOf(0) }
    var currentPage by remember { mutableStateOf(1) }

    val notifier = rememberNotifier()
    val scope = rememberCoroutineScope()

    /** Items from the last successful generate, and the QR built from them. */
    var generated by remember { mutableStateOf<List<GeneratedItem>>(emptyList()) }
    var qrBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var busy by remember { mutableStateOf(false) }

    val categories = listOf(
        "All", "Alphabet", "Numbers", "Animals", "Colors",
        "My Body", "Fruits & Vegetables", "Classroom Objects", "Stories", "Activities",
    )

    val worksheets = remember {
        listOf(
            WorksheetItem("Alphabet (वर्णमाला)", "Hindi ↔ Mundari", "Class 1 • 4 pages", 0),
            WorksheetItem("Numbers (1 – 10)", "Hindi ↔ Mundari", "Class 1 • 3 pages", 1),
            WorksheetItem("Animals (जानवर)", "Hindi ↔ Mundari", "Class 1 • 4 pages", 2),
            WorksheetItem("Colors (रंग)", "Hindi ↔ Mundari", "Class 1 • 2 pages", 3),
            WorksheetItem("Fruits (फल)", "Hindi ↔ Mundari", "Class 1 • 3 pages", 4),
            WorksheetItem("My Body (शरीर के अंग)", "Hindi ↔ Mundari", "Class 1 • 4 pages", 5),
            WorksheetItem("Classroom Objects", "Hindi ↔ Mundari", "Class 1 • 3 pages", 6),
            WorksheetItem("Tracing Practice", "Hindi ↔ Mundari", "Class 1 • 5 pages", 7),
            WorksheetItem("Short Stories (छोटी कहानियाँ)", "Hindi ↔ Mundari", "Class 1 • 4 pages", 8),
        )
    }

    val worksheetTitle = worksheets.getOrNull(selectedWorksheetIndex)?.title ?: "Worksheet"

    /**
     * Generates a bilingual worksheet, then announces the real outcome.
     *
     * Runs the actual [WorksheetAssembler] against [NumeracySeed]'s authored pool, so the popup
     * reports a count that exists. Every branch of [AssemblyResult] gets its own message — a
     * notification claiming success when the pool was deficient would be exactly the kind of lie
     * the provenance system exists to stop, and the assembler already hands back a diagnosis.
     */
    fun generateWorksheet() {
        if (busy) return
        busy = true
        scope.launch {
            try {
                val result = withContext(Dispatchers.Default) {
                    WorksheetAssembler.assemble(
                        // Seeded from the clock so repeated taps give a fresh sheet, and the seed
                        // is what makes any one sheet reprintable.
                        spec = NumeracySeed.spec(seed = System.currentTimeMillis()),
                        models = NumeracySeed.models,
                    )
                }
                when (result) {
                    is AssemblyResult.Success -> {
                        generated = result.items
                        // A new sheet invalidates the QR built from the old one.
                        qrBitmap = null
                        val relaxed = result.relaxations
                        notifier.show(
                            AppNotice(
                                title = "Worksheet ready",
                                message = if (relaxed.isEmpty()) {
                                    "${result.items.size} bilingual items generated for " +
                                        "Hindi ↔ ${selectedLang.englishName}."
                                } else {
                                    "${result.items.size} items generated, with " +
                                        "${relaxed.size} constraint relaxed: " +
                                        relaxed.first().constraint
                                },
                                messageHi = "वर्कशीट तैयार है — ${result.items.size} प्रश्न",
                                kind = if (relaxed.isEmpty()) NoticeKind.SUCCESS else NoticeKind.WARNING,
                            ),
                        )
                    }
                    is AssemblyResult.DeficientPool -> notifier.show(
                        AppNotice(
                            title = "Could not fill the sheet",
                            message = "Only ${result.availableAfterFiltering} of " +
                                "${result.required} items were available. More items need authoring.",
                            kind = NoticeKind.WARNING,
                        ),
                    )
                    is AssemblyResult.NoItemModels -> notifier.show(
                        AppNotice(
                            title = "Nothing to generate yet",
                            message = "No item models exist for ${result.lakshyaCode}.",
                            kind = NoticeKind.WARNING,
                        ),
                    )
                }
            } finally {
                busy = false
            }
        }
    }

    /** Encodes the generated sheet as a QR code, then announces it. */
    fun generateQr() {
        if (busy) return
        if (generated.isEmpty()) {
            notifier.show(
                AppNotice(
                    title = "Generate the worksheet first",
                    message = "There is nothing to put in a QR code yet.",
                    kind = NoticeKind.WARNING,
                ),
            )
            return
        }
        busy = true
        scope.launch {
            try {
                val payload = QrCode.payloadFor(worksheetTitle, generated)
                // Encoding allocates a bitmap and runs Reed-Solomon; off the main thread.
                val bmp = withContext(Dispatchers.Default) { QrCode.encode(payload) }
                qrBitmap = bmp
                notifier.show(
                    if (bmp != null) {
                        AppNotice(
                            title = "QR code generated",
                            message = "Scan it with any camera to read the worksheet. " +
                                "Nothing is uploaded — the sheet itself is in the code.",
                            messageHi = "क्यूआर कोड तैयार है",
                        )
                    } else {
                        AppNotice(
                            title = "QR code could not be made",
                            message = "This worksheet is too long to fit in one code.",
                            kind = NoticeKind.WARNING,
                        )
                    },
                )
            } finally {
                busy = false
            }
        }
    }

    NotificationHost(notifier)

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        // 1. Header Banner
        BannerHeaderCard(
            icon = Icons.AutoMirrored.Filled.List,
            title = "Worksheets",
            subtitleEn = "Generate and download bilingual worksheets for early learning",
            subtitleHi = "सीखने के लिए द्विभाषी वर्कशीट बनाएं और डाउनलोड करें",
            badgeLines = listOf("Learn", "Practice", "Grow", "Together"),
        )

        // 2. Language Selector Bar + Search Field
        LanguageSelectorBar(
            currentLanguage = selectedLang,
            onSelectLanguage = { selectedLang = it },
            label = "Select Language",
            trailingContent = {
                // Search Input box
                Row(
                    modifier = Modifier
                        .weight(1f)
                        .background(Color.White, RoundedCornerShape(12.dp))
                        .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(12.dp))
                        .padding(horizontal = 12.dp, vertical = 9.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    Icon(Icons.Filled.Search, null, Modifier.size(16.dp), tint = Color(0xFF94A3B8))
                    Text(
                        if (searchQuery.isEmpty()) "Search worksheets... (e.g., numbers, animals, alphabet)" else searchQuery,
                        style = MaterialTheme.typography.bodySmall.copy(
                            fontSize = 12.sp,
                            color = if (searchQuery.isEmpty()) Color(0xFF94A3B8) else Color(0xFF1E293B),
                        ),
                        modifier = Modifier.weight(1f),
                    )
                    Text("⇄", color = Color(0xFF16A34A), fontSize = 14.sp)
                }
            },
        )

        // 3. Category Filter Chips Row
        LazyRow(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            items(categories.size) { idx ->
                val isSelected = selectedCategory == idx
                Box(
                    modifier = Modifier
                        .background(
                            if (isSelected) Color(0xFF2EAF3B) else Color.White,
                            RoundedCornerShape(20.dp),
                        )
                        .border(
                            1.dp,
                            if (isSelected) Color(0xFF259B32) else Color(0xFFE2E8F0),
                            RoundedCornerShape(20.dp),
                        )
                        .clickable { selectedCategory = idx }
                        .padding(horizontal = 14.dp, vertical = 6.dp),
                ) {
                    Text(
                        categories[idx],
                        style = MaterialTheme.typography.labelSmall.copy(
                            fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Medium,
                            fontSize = 11.5.sp,
                            color = if (isSelected) Color.White else Color(0xFF475569),
                        ),
                    )
                }
            }
        }

        // 4. Main Section: 3x3 Worksheet Cards Grid + Right Preview Drawer
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(14.dp),
        ) {
            // Left: Grid of Worksheets (weight 1.9f)
            LazyVerticalGrid(
                columns = GridCells.Fixed(3),
                modifier = Modifier
                    .weight(1.9f)
                    .height(440.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp),
                horizontalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                itemsIndexed(worksheets) { index, item ->
                    val isSelected = selectedWorksheetIndex == index
                    WorksheetCard(
                        item = item,
                        isSelected = isSelected,
                        onClick = { selectedWorksheetIndex = index },
                    )
                }
            }

            // Right: Worksheet Preview Panel (weight 1.1f)
            Box(
                modifier = Modifier
                    .weight(1.1f)
                    .height(440.dp)
                    .background(Color.White, RoundedCornerShape(16.dp))
                    .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(16.dp))
                    .padding(14.dp),
            ) {
                Column(
                    modifier = Modifier.fillMaxSize(),
                    verticalArrangement = Arrangement.SpaceBetween,
                ) {
                    // Preview Header
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text(
                            worksheets[selectedWorksheetIndex].title,
                            style = MaterialTheme.typography.titleMedium.copy(
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp,
                                color = Color(0xFF1E293B),
                            ),
                        )
                        Icon(
                            Icons.Filled.Close,
                            contentDescription = "Close",
                            tint = Color(0xFF64748B),
                            modifier = Modifier.size(16.dp),
                        )
                    }

                    Spacer(Modifier.height(6.dp))

                    // Embedded worksheet canvas preview
                    WorksheetPreviewSheet(
                        modifier = Modifier
                            .fillMaxWidth()
                            .weight(1f),
                    )

                    Spacer(Modifier.height(8.dp))

                    // Pagination controls: < 1 / 4 >
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.Center,
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Icon(
                            Icons.AutoMirrored.Filled.KeyboardArrowLeft,
                            contentDescription = null,
                            modifier = Modifier
                                .size(20.dp)
                                .clickable { if (currentPage > 1) currentPage-- },
                            tint = Color(0xFF64748B),
                        )
                        Spacer(Modifier.width(10.dp))
                        Text(
                            "$currentPage / 4",
                            style = MaterialTheme.typography.labelSmall.copy(
                                fontSize = 11.5.sp,
                                fontWeight = FontWeight.SemiBold,
                                color = Color(0xFF1E293B),
                            ),
                        )
                        Spacer(Modifier.width(10.dp))
                        Icon(
                            Icons.AutoMirrored.Filled.KeyboardArrowRight,
                            contentDescription = null,
                            modifier = Modifier
                                .size(20.dp)
                                .clickable { if (currentPage < 4) currentPage++ },
                            tint = Color(0xFF64748B),
                        )
                        Spacer(Modifier.width(16.dp))
                        Text("⛶", fontSize = 13.sp, color = Color(0xFF64748B))
                    }

                    Spacer(Modifier.height(8.dp))

                    // Generate button. Runs the real assembler; the popup reports what came back.
                    Button(
                        onClick = { generateWorksheet() },
                        enabled = !busy,
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF2EAF3B)),
                        shape = RoundedCornerShape(10.dp),
                        modifier = Modifier.fillMaxWidth().height(48.dp),
                    ) {
                        Text(
                            if (busy) "Generating…" else "✨  Generate worksheet",
                            color = Color.White,
                            fontWeight = FontWeight.Bold,
                            fontSize = 14.sp,
                        )
                    }

                    if (generated.isNotEmpty()) {
                        Spacer(Modifier.height(6.dp))
                        Text(
                            "${generated.size} items ready · " +
                                "${generated.map { it.strategy }.distinct().size} question types",
                            style = MaterialTheme.typography.bodySmall.copy(
                                fontSize = 14.sp,
                                color = Color(0xFF1B5E20),
                                fontWeight = FontWeight.SemiBold,
                            ),
                        )
                    }

                    Spacer(Modifier.height(6.dp))

                    // Download PDF button (Green)
                    Button(
                        onClick = { /* download pdf action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF2EAF3B)),
                        shape = RoundedCornerShape(10.dp),
                        modifier = Modifier.fillMaxWidth().height(42.dp),
                    ) {
                        Text("📥  Download PDF", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                    }

                    Spacer(Modifier.height(6.dp))

                    // Action buttons row: Preview All Pages | Share
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                    ) {
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .background(Color(0xFFF8FAFC), RoundedCornerShape(8.dp))
                                .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(8.dp))
                                .padding(vertical = 6.dp),
                            contentAlignment = Alignment.Center,
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                Text("👁", fontSize = 11.sp)
                                Text("Preview All Pages", fontSize = 10.5.sp, color = Color(0xFF334155))
                            }
                        }

                        Box(
                            modifier = Modifier
                                .weight(0.7f)
                                .background(Color(0xFFF8FAFC), RoundedCornerShape(8.dp))
                                .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(8.dp))
                                .clickable(enabled = !busy) { generateQr() }
                                .padding(vertical = 6.dp),
                            contentAlignment = Alignment.Center,
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                Icon(Icons.Filled.Share, null, Modifier.size(11.dp), tint = Color(0xFF334155))
                                Text("Generate QR", fontSize = 10.5.sp, color = Color(0xFF334155))
                            }
                        }
                    }

                    // The QR itself, once made. Shown here rather than in a dialog so the teacher
                    // can hold the tablet up to a row of phones without a modal in the way.
                    qrBitmap?.let { bmp ->
                        Spacer(Modifier.height(8.dp))
                        Column(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Image(
                                bitmap = bmp.asImageBitmap(),
                                contentDescription =
                                    "QR code containing the $worksheetTitle worksheet",
                                modifier = Modifier
                                    .size(160.dp)
                                    .background(Color.White, RoundedCornerShape(8.dp))
                                    .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(8.dp))
                                    .padding(6.dp),
                            )
                            Spacer(Modifier.height(4.dp))
                            Text(
                                "Scan to read · कैमरे से स्कैन करें",
                                style = MaterialTheme.typography.bodySmall.copy(
                                    fontSize = 14.sp,
                                    color = Color(0xFF475569),
                                ),
                            )
                        }
                    }

                    Spacer(Modifier.height(6.dp))

                    // NIPUN Bharat link
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.Center,
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text("📖 ", fontSize = 11.sp)
                        Text(
                            "Aligned with NIPUN Bharat FLN outcomes →",
                            style = MaterialTheme.typography.labelSmall.copy(fontSize = 10.sp, color = Color(0xFF475569)),
                        )
                    }
                }
            }
        }

        // 5. Footer Bar
        FooterTipBar(
            tipText = "Use the search to find specific worksheets like 'counting', 'animals', or 'my body' in your selected language.",
            actionText = "Want a custom worksheet? Generate with AI →",
        )
    }
}

@Composable
private fun WorksheetCard(
    item: WorksheetItem,
    isSelected: Boolean,
    onClick: () -> Unit,
) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .background(Color.White, RoundedCornerShape(14.dp))
            .border(
                1.2.dp,
                if (isSelected) Color(0xFF2EAF3B) else Color(0xFFE2E8F0),
                RoundedCornerShape(14.dp),
            )
            .clickable(onClick = onClick)
            .padding(10.dp),
    ) {
        Column(modifier = Modifier.fillMaxWidth()) {
            // Thumbnail Canvas area
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(64.dp)
                    .background(Color(0xFFF8FAFC), RoundedCornerShape(8.dp)),
                contentAlignment = Alignment.Center,
            ) {
                WorksheetThumbnail(categoryIndex = item.categoryIndex)
            }

            Spacer(Modifier.height(8.dp))

            // Title
            Text(
                item.title,
                style = MaterialTheme.typography.bodyMedium.copy(
                    fontWeight = FontWeight.Bold,
                    fontSize = 12.5.sp,
                    color = Color(0xFF1E293B),
                ),
            )

            // Subtitle & Pages + Download button
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.Bottom,
            ) {
                Column {
                    Text(
                        item.subtitle,
                        style = MaterialTheme.typography.labelSmall.copy(fontSize = 10.sp, color = Color(0xFF64748B)),
                    )
                    Text(
                        item.gradePages,
                        style = MaterialTheme.typography.labelSmall.copy(fontSize = 9.5.sp, color = Color(0xFF94A3B8)),
                    )
                }

                // Download icon button
                Box(
                    modifier = Modifier
                        .size(24.dp)
                        .background(Color(0xFF2EAF3B), CircleShape),
                    contentAlignment = Alignment.Center,
                ) {
                    Text("↓", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                }
            }
        }
    }
}
