package org.bolmitra.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowLeft
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowRight
import androidx.compose.material.icons.automirrored.filled.List
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import android.graphics.Bitmap
import androidx.compose.foundation.Image
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.graphics.asImageBitmap
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import org.bolmitra.curriculum.AssemblyResult
import org.bolmitra.curriculum.GeneratedItem
import org.bolmitra.curriculum.LessonWorksheet
import org.bolmitra.curriculum.NumeracySeed
import org.bolmitra.curriculum.QrCode
import org.bolmitra.curriculum.WorksheetAssembler
import org.bolmitra.data.TurnRecorder
import org.bolmitra.phrasebook.Provenance
import org.bolmitra.speech.TargetLanguage
import org.bolmitra.ui.common.AppNotice
import org.bolmitra.ui.common.NoticeKind
import org.bolmitra.ui.common.NotificationHost
import org.bolmitra.ui.common.OlChikiFont
import org.bolmitra.ui.common.WorksheetPreviewSheet
import org.bolmitra.ui.common.WorksheetThumbnail
import org.bolmitra.ui.common.rememberNotifier

data class WorksheetItem(
    val title: String,
    val subtitle: String,
    val gradePages: String,
    val categoryIndex: Int,
)

/**
 * Worksheets Screen — Exact replica of Image 3.
 */
@Composable
fun WorksheetsScreenPane(
    wide: Boolean,
    modifier: Modifier = Modifier,
) {
    var selectedLang by remember { mutableStateOf(TargetLanguage.MUNDARI) }
    var searchQuery by remember { mutableStateOf("") }
    var selectedCategory by remember { mutableStateOf(0) } // 0: All
    var selectedWorksheetIndex by remember { mutableStateOf(0) }
    var currentPage by remember { mutableStateOf(1) }

    val context = LocalContext.current
    val notifier = rememberNotifier()
    val scope = rememberCoroutineScope()

    /** Items from the last successful generate, and the QR built from them. */
    var generated by remember { mutableStateOf<List<GeneratedItem>>(emptyList()) }
    var qrBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var busy by remember { mutableStateOf(false) }

    val categories = listOf(
        "All", "Alphabet", "Numbers", "Animals", "Colors",
        "My Body", "Fruits & Vegetables", "Classroom Objects", "Stories", "Activities",
    )

    /**
     * The lesson recap, built from the turns that actually happened.
     *
     * Rebuilt whenever the language changes or the screen is re-entered, so walking here straight from
     * a Live Class session shows that session. `recapReloads` lets the Regenerate button re-stamp it.
     */
    val recorder = remember { TurnRecorder(context) }
    var recap by remember { mutableStateOf<LessonWorksheet.Sheet?>(null) }
    var recapReloads by remember { mutableStateOf(0) }

    LaunchedEffect(selectedLang, recapReloads) {
        val turns = recorder.forWorksheet(selectedLang)
        recap = LessonWorksheet.from(
            turns = turns,
            languageName = selectedLang.englishName,
            nowMs = System.currentTimeMillis(),
        )
    }

    // The first card is real: it reports the row count the recap actually holds. The rest are authored
    // categories whose subtitle now follows the selected language instead of always claiming Mundari.
    val worksheets = remember(selectedLang, recap) {
        val pair = "Hindi \u2194 ${selectedLang.englishName}"
        val recapRows = recap?.rows?.size ?: 0
        listOf(
            WorksheetItem(
                title = "Lesson recap (from history)",
                subtitle = pair,
                gradePages = if (recapRows == 0) {
                    "No lessons recorded yet"
                } else {
                    "$recapRows ${if (recapRows == 1) "phrase" else "phrases"} from your class"
                },
                categoryIndex = 0,
            ),
            WorksheetItem("Alphabet (वर्णमाला)", pair, "Class 1 • Alphabet", 0),
            WorksheetItem("Numbers (1 – 10)", pair, "Class 1 • Numeracy", 1),
            WorksheetItem("Animals (जानवर)", pair, "Class 1 • Vocabulary", 2),
            WorksheetItem("Colors (रंग)", pair, "Class 1 • Vocabulary", 3),
            WorksheetItem("Fruits (फल)", pair, "Class 1 • Vocabulary", 4),
            WorksheetItem("My Body (शरीर के अंग)", pair, "Class 1 • Vocabulary", 5),
            WorksheetItem("Classroom Objects", pair, "Class 1 • Vocabulary", 6),
            WorksheetItem("Tracing Practice", pair, "Class 1 • Writing", 7),
        )
    }

    val worksheetTitle = worksheets.getOrNull(selectedWorksheetIndex)?.title ?: "Worksheet"

    /** The recap is card 0. Only it has real content to preview. */
    val showingRecap = selectedWorksheetIndex == 0

    /**
     * Generates a bilingual worksheet, then announces the real outcome.
     *
     * Runs the actual [WorksheetAssembler] against [NumeracySeed]'s authored pool, so the popup
     * reports a count that exists. Every branch of [AssemblyResult] gets its own message — a
     * notification claiming success when the pool was deficient would be exactly the kind of lie
     * the provenance system exists to stop, and the assembler already hands back a diagnosis.
     */
    fun generateWorksheet() {
        if (busy) return
        busy = true
        scope.launch {
            try {
                val result = withContext(Dispatchers.Default) {
                    WorksheetAssembler.assemble(
                        // Seeded from the clock so repeated taps give a fresh sheet, and the seed
                        // is what makes any one sheet reprintable.
                        spec = NumeracySeed.spec(seed = System.currentTimeMillis()),
                        models = NumeracySeed.models,
                    )
                }
                when (result) {
                    is AssemblyResult.Success -> {
                        generated = result.items
                        // A new sheet invalidates the QR built from the old one.
                        qrBitmap = null
                        val relaxed = result.relaxations
                        notifier.show(
                            AppNotice(
                                title = "Worksheet ready",
                                message = if (relaxed.isEmpty()) {
                                    "${result.items.size} bilingual items generated for " +
                                        "Hindi ↔ ${selectedLang.englishName}."
                                } else {
                                    "${result.items.size} items generated, with " +
                                        "${relaxed.size} constraint relaxed: " +
                                        relaxed.first().constraint
                                },
                                messageHi = "वर्कशीट तैयार है — ${result.items.size} प्रश्न",
                                kind = if (relaxed.isEmpty()) NoticeKind.SUCCESS else NoticeKind.WARNING,
                            ),
                        )
                    }
                    is AssemblyResult.DeficientPool -> notifier.show(
                        AppNotice(
                            title = "Could not fill the sheet",
                            message = "Only ${result.availableAfterFiltering} of " +
                                "${result.required} items were available. More items need authoring.",
                            kind = NoticeKind.WARNING,
                        ),
                    )
                    is AssemblyResult.NoItemModels -> notifier.show(
                        AppNotice(
                            title = "Nothing to generate yet",
                            message = "No item models exist for ${result.lakshyaCode}.",
                            kind = NoticeKind.WARNING,
                        ),
                    )
                }
            } finally {
                busy = false
            }
        }
    }

    /** Encodes the generated sheet as a QR code, then announces it. */
    fun generateQr() {
        if (busy) return
        if (generated.isEmpty()) {
            notifier.show(
                AppNotice(
                    title = "Generate the worksheet first",
                    message = "There is nothing to put in a QR code yet.",
                    kind = NoticeKind.WARNING,
                ),
            )
            return
        }
        busy = true
        scope.launch {
            try {
                val payload = QrCode.payloadFor(worksheetTitle, generated)
                // Encoding allocates a bitmap and runs Reed-Solomon; off the main thread.
                val bmp = withContext(Dispatchers.Default) { QrCode.encode(payload) }
                qrBitmap = bmp
                notifier.show(
                    if (bmp != null) {
                        AppNotice(
                            title = "QR code generated",
                            message = "Scan it with any camera to read the worksheet. " +
                                "Nothing is uploaded — the sheet itself is in the code.",
                            messageHi = "क्यूआर कोड तैयार है",
                        )
                    } else {
                        AppNotice(
                            title = "QR code could not be made",
                            message = "This worksheet is too long to fit in one code.",
                            kind = NoticeKind.WARNING,
                        )
                    },
                )
            } finally {
                busy = false
            }
        }
    }

    NotificationHost(notifier)

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        // 1. Header Banner
        BannerHeaderCard(
            icon = Icons.AutoMirrored.Filled.List,
            title = "Worksheets",
            subtitleEn = "Generate and download bilingual worksheets for early learning",
            subtitleHi = "सीखने के लिए द्विभाषी वर्कशीट बनाएं और डाउनलोड करें",
            badgeLines = listOf("Learn", "Practice", "Grow", "Together"),
        )

        // 2. Language Selector Bar + Search Field
        LanguageSelectorBar(
            currentLanguage = selectedLang,
            onSelectLanguage = { selectedLang = it },
            label = "Select Language",
            trailingContent = {
                // Search Input box
                Row(
                    modifier = Modifier
                        .weight(1f)
                        .background(Color.White, RoundedCornerShape(12.dp))
                        .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(12.dp))
                        .padding(horizontal = 12.dp, vertical = 9.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    Icon(Icons.Filled.Search, null, Modifier.size(16.dp), tint = Color(0xFF94A3B8))
                    Text(
                        if (searchQuery.isEmpty()) "Search worksheets... (e.g., numbers, animals, alphabet)" else searchQuery,
                        style = MaterialTheme.typography.bodySmall.copy(
                            fontSize = 12.sp,
                            color = if (searchQuery.isEmpty()) Color(0xFF94A3B8) else Color(0xFF1E293B),
                        ),
                        modifier = Modifier.weight(1f),
                    )
                    Text("⇄", color = Color(0xFF16A34A), fontSize = 14.sp)
                }
            },
        )

        // 3. Category Filter Chips Row
        LazyRow(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            items(categories.size) { idx ->
                val isSelected = selectedCategory == idx
                Box(
                    modifier = Modifier
                        .background(
                            if (isSelected) Color(0xFF2EAF3B) else Color.White,
                            RoundedCornerShape(20.dp),
                        )
                        .border(
                            1.dp,
                            if (isSelected) Color(0xFF259B32) else Color(0xFFE2E8F0),
                            RoundedCornerShape(20.dp),
                        )
                        .clickable { selectedCategory = idx }
                        .padding(horizontal = 14.dp, vertical = 6.dp),
                ) {
                    Text(
                        categories[idx],
                        style = MaterialTheme.typography.labelSmall.copy(
                            fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Medium,
                            fontSize = 11.5.sp,
                            color = if (isSelected) Color.White else Color(0xFF475569),
                        ),
                    )
                }
            }
        }

        // 4. Main Section: 3x3 Worksheet Cards Grid + Right Preview Drawer
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(14.dp),
        ) {
            // Left: Grid of Worksheets (weight 1.9f)
            LazyVerticalGrid(
                columns = GridCells.Fixed(3),
                modifier = Modifier
                    .weight(1.9f)
                    .height(440.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp),
                horizontalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                itemsIndexed(worksheets) { index, item ->
                    val isSelected = selectedWorksheetIndex == index
                    WorksheetCard(
                        item = item,
                        isSelected = isSelected,
                        onClick = { selectedWorksheetIndex = index },
                    )
                }
            }

            // Right: Worksheet Preview Panel (weight 1.1f)
            Box(
                modifier = Modifier
                    .weight(1.1f)
                    .height(440.dp)
                    .background(Color.White, RoundedCornerShape(16.dp))
                    .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(16.dp))
                    .padding(14.dp),
            ) {
                Column(
                    modifier = Modifier.fillMaxSize(),
                    verticalArrangement = Arrangement.SpaceBetween,
                ) {
                    // Preview Header
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text(
                            worksheets[selectedWorksheetIndex].title,
                            style = MaterialTheme.typography.titleMedium.copy(
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp,
                                color = Color(0xFF1E293B),
                            ),
                        )
                        Icon(
                            Icons.Filled.Close,
                            contentDescription = "Close",
                            tint = Color(0xFF64748B),
                            modifier = Modifier.size(16.dp),
                        )
                    }

                    Spacer(Modifier.height(6.dp))

                    // The recap renders its real rows; every other card still shows the illustrative
                    // canvas, because no content has been authored for those yet and drawing rows
                    // there would imply otherwise.
                    val sheet = recap
                    if (showingRecap && sheet != null && !sheet.isEmpty) {
                        LessonRecapPreview(
                            sheet = sheet,
                            page = currentPage,
                            modifier = Modifier.fillMaxWidth().weight(1f),
                        )
                    } else if (showingRecap) {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .weight(1f)
                                .background(Color(0xFFF8FAFC), RoundedCornerShape(10.dp)),
                            contentAlignment = Alignment.Center,
                        ) {
                            Text(
                                "Teach a Live Class first.\nWhat you say there becomes this sheet.",
                                style = MaterialTheme.typography.bodySmall.copy(
                                    fontSize = 12.sp,
                                    color = Color(0xFF94A3B8),
                                ),
                            )
                        }
                    } else {
                        WorksheetPreviewSheet(
                            modifier = Modifier
                                .fillMaxWidth()
                                .weight(1f),
                        )
                    }

                    Spacer(Modifier.height(8.dp))

                    // Pagination derived from the content. The "/ 4" here was a literal, so it
                    // claimed four pages for every sheet including empty ones.
                    val pageCount = if (showingRecap && sheet != null) {
                        maxOf(1, (sheet.rows.size + RECAP_ROWS_PER_PAGE - 1) / RECAP_ROWS_PER_PAGE)
                    } else {
                        1
                    }
                    if (currentPage > pageCount) currentPage = pageCount

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.Center,
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Icon(
                            Icons.AutoMirrored.Filled.KeyboardArrowLeft,
                            contentDescription = "Previous page",
                            modifier = Modifier
                                .size(20.dp)
                                .clickable { if (currentPage > 1) currentPage-- },
                            tint = Color(0xFF64748B),
                        )
                        Spacer(Modifier.width(10.dp))
                        Text(
                            "$currentPage / $pageCount",
                            style = MaterialTheme.typography.labelSmall.copy(
                                fontSize = 11.5.sp,
                                fontWeight = FontWeight.SemiBold,
                                color = Color(0xFF1E293B),
                            ),
                        )
                        Spacer(Modifier.width(10.dp))
                        Icon(
                            Icons.AutoMirrored.Filled.KeyboardArrowRight,
                            contentDescription = "Next page",
                            modifier = Modifier
                                .size(20.dp)
                                .clickable { if (currentPage < pageCount) currentPage++ },
                            tint = Color(0xFF64748B),
                        )
                    }

                    Spacer(Modifier.height(8.dp))

                    // Generate button. Runs the real assembler; the popup reports what came back.
                    Button(
                        onClick = { generateWorksheet() },
                        enabled = !busy,
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF2EAF3B)),
                        shape = RoundedCornerShape(10.dp),
                        modifier = Modifier.fillMaxWidth().height(48.dp),
                    ) {
                        Text(
                            if (busy) "Generating…" else "✨  Generate worksheet",
                            color = Color.White,
                            fontWeight = FontWeight.Bold,
                            fontSize = 14.sp,
                        )
                    }

                    if (generated.isNotEmpty()) {
                        Spacer(Modifier.height(6.dp))
                        Text(
                            "${generated.size} items ready · " +
                                "${generated.map { it.strategy }.distinct().size} question types",
                            style = MaterialTheme.typography.bodySmall.copy(
                                fontSize = 14.sp,
                                color = Color(0xFF1B5E20),
                                fontWeight = FontWeight.SemiBold,
                            ),
                        )
                    }

                    Spacer(Modifier.height(6.dp))

                    // Download PDF button (Green)
                    Button(
                        onClick = { /* download pdf action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF2EAF3B)),
                        shape = RoundedCornerShape(10.dp),
                        modifier = Modifier.fillMaxWidth().height(42.dp),
                    ) {
                        Text("📥  Download PDF", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 13.sp)
                    }

                    Spacer(Modifier.height(6.dp))

                    // Action buttons row: Preview All Pages | Share
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                    ) {
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .background(Color(0xFFF8FAFC), RoundedCornerShape(8.dp))
                                .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(8.dp))
                                .padding(vertical = 6.dp),
                            contentAlignment = Alignment.Center,
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                Text("👁", fontSize = 11.sp)
                                Text("Preview All Pages", fontSize = 10.5.sp, color = Color(0xFF334155))
                            }
                        }

                        Box(
                            modifier = Modifier
                                .weight(0.7f)
                                .background(Color(0xFFF8FAFC), RoundedCornerShape(8.dp))
                                .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(8.dp))
                                .clickable(enabled = !busy) { generateQr() }
                                .padding(vertical = 6.dp),
                            contentAlignment = Alignment.Center,
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                Icon(Icons.Filled.Share, null, Modifier.size(11.dp), tint = Color(0xFF334155))
                                Text("Generate QR", fontSize = 10.5.sp, color = Color(0xFF334155))
                            }
                        }
                    }

                    // The QR itself, once made. Shown here rather than in a dialog so the teacher
                    // can hold the tablet up to a row of phones without a modal in the way.
                    qrBitmap?.let { bmp ->
                        Spacer(Modifier.height(8.dp))
                        Column(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Image(
                                bitmap = bmp.asImageBitmap(),
                                contentDescription =
                                    "QR code containing the $worksheetTitle worksheet",
                                modifier = Modifier
                                    .size(160.dp)
                                    .background(Color.White, RoundedCornerShape(8.dp))
                                    .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(8.dp))
                                    .padding(6.dp),
                            )
                            Spacer(Modifier.height(4.dp))
                            Text(
                                "Scan to read · कैमरे से स्कैन करें",
                                style = MaterialTheme.typography.bodySmall.copy(
                                    fontSize = 14.sp,
                                    color = Color(0xFF475569),
                                ),
                            )
                        }
                    }

                    Spacer(Modifier.height(6.dp))

                    // NIPUN Bharat link
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.Center,
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text("📖 ", fontSize = 11.sp)
                        Text(
                            "Aligned with NIPUN Bharat FLN outcomes →",
                            style = MaterialTheme.typography.labelSmall.copy(fontSize = 10.sp, color = Color(0xFF475569)),
                        )
                    }
                }
            }
        }

        // 5. Footer Bar
        FooterTipBar(
            tipText = "Use the search to find specific worksheets like 'counting', 'animals', or 'my body' in your selected language.",
            actionText = "Want a custom worksheet? Generate with AI →",
        )
    }
}

@Composable
private fun WorksheetCard(
    item: WorksheetItem,
    isSelected: Boolean,
    onClick: () -> Unit,
) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .background(Color.White, RoundedCornerShape(14.dp))
            .border(
                1.2.dp,
                if (isSelected) Color(0xFF2EAF3B) else Color(0xFFE2E8F0),
                RoundedCornerShape(14.dp),
            )
            .clickable(onClick = onClick)
            .padding(10.dp),
    ) {
        Column(modifier = Modifier.fillMaxWidth()) {
            // Thumbnail Canvas area
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(64.dp)
                    .background(Color(0xFFF8FAFC), RoundedCornerShape(8.dp)),
                contentAlignment = Alignment.Center,
            ) {
                WorksheetThumbnail(categoryIndex = item.categoryIndex)
            }

            Spacer(Modifier.height(8.dp))

            // Title
            Text(
                item.title,
                style = MaterialTheme.typography.bodyMedium.copy(
                    fontWeight = FontWeight.Bold,
                    fontSize = 12.5.sp,
                    color = Color(0xFF1E293B),
                ),
            )

            // Subtitle & Pages + Download button
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.Bottom,
            ) {
                Column {
                    Text(
                        item.subtitle,
                        style = MaterialTheme.typography.labelSmall.copy(fontSize = 10.sp, color = Color(0xFF64748B)),
                    )
                    Text(
                        item.gradePages,
                        style = MaterialTheme.typography.labelSmall.copy(fontSize = 9.5.sp, color = Color(0xFF94A3B8)),
                    )
                }

                // Download icon button
                Box(
                    modifier = Modifier
                        .size(24.dp)
                        .background(Color(0xFF2EAF3B), CircleShape),
                    contentAlignment = Alignment.Center,
                ) {
                    Text("↓", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                }
            }
        }
    }
}

/** Rows that fit on one previewed page. Also what the pagination arithmetic divides by. */
private const val RECAP_ROWS_PER_PAGE = 6

/**
 * Renders the lesson recap: real bilingual rows, when it was generated, and how much of it no human
 * has checked.
 *
 * The generation stamp and the covered window are both shown because they answer different questions.
 * "Generated 2:14 PM" says how fresh the sheet is; "covers 1:52 PM – 2:09 PM" says which lesson it
 * came from. A teacher printing a sheet an hour later needs the second one.
 *
 * Ol Chiki goes through [OlChikiFont.annotate] rather than being set as the whole-Text family: the
 * bundled face carries 53 codepoints and no Devanagari, so a Mundari recap would tofu entirely.
 */
@Composable
private fun LessonRecapPreview(
    sheet: LessonWorksheet.Sheet,
    page: Int,
    modifier: Modifier = Modifier,
) {
    val from = (page - 1) * RECAP_ROWS_PER_PAGE
    val rows = sheet.rows.drop(from).take(RECAP_ROWS_PER_PAGE)
    val clock = remember { SimpleDateFormat("h:mm a", Locale.getDefault()) }
    val stamp = remember { SimpleDateFormat("d MMM yyyy, h:mm a", Locale.getDefault()) }

    Column(
        modifier = modifier
            .background(Color.White, RoundedCornerShape(10.dp))
            .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(10.dp))
            .padding(10.dp),
    ) {
        Text(
            "${sheet.title} · Hindi \u2194 ${sheet.languageName}",
            style = MaterialTheme.typography.labelMedium.copy(
                fontWeight = FontWeight.Bold,
                fontSize = 11.5.sp,
                color = Color(0xFF14532D),
            ),
        )
        // The date and time the user asked to see on the sheet.
        Text(
            "Generated ${stamp.format(Date(sheet.generatedAtMs))}",
            style = MaterialTheme.typography.labelSmall.copy(fontSize = 9.5.sp, color = Color(0xFF64748B)),
        )
        if (sheet.coversFromMs != null && sheet.coversToMs != null) {
            Text(
                "Covers ${clock.format(Date(sheet.coversFromMs))} – " +
                    clock.format(Date(sheet.coversToMs)),
                style = MaterialTheme.typography.labelSmall.copy(fontSize = 9.5.sp, color = Color(0xFF94A3B8)),
            )
        }

        Spacer(Modifier.height(6.dp))
        HorizontalDivider(color = Color(0xFFF1F5F9))
        Spacer(Modifier.height(4.dp))

        rows.forEachIndexed { i, row ->
            Row(
                modifier = Modifier.fillMaxWidth().padding(vertical = 3.dp),
                verticalAlignment = Alignment.Top,
            ) {
                Text(
                    "${from + i + 1}.",
                    style = MaterialTheme.typography.labelSmall.copy(
                        fontSize = 10.sp,
                        color = Color(0xFF94A3B8),
                    ),
                    modifier = Modifier.width(18.dp),
                )
                Column(modifier = Modifier.weight(1f)) {
                    Text(
                        row.hindi,
                        style = MaterialTheme.typography.bodySmall.copy(
                            fontWeight = FontWeight.SemiBold,
                            fontSize = 11.5.sp,
                            color = Color(0xFF1E293B),
                        ),
                    )
                    Text(
                        text = OlChikiFont.annotate(row.target),
                        style = MaterialTheme.typography.bodySmall.copy(
                            fontSize = 11.5.sp,
                            color = Color(0xFF166534),
                        ),
                    )
                }
                // Per-row level, so a machine guess is never indistinguishable from a reviewed phrase
                // on a printed page.
                Text(
                    when (row.provenance) {
                        Provenance.VERIFIED -> "verified"
                        Provenance.CORPUS -> row.src ?: "corpus"
                        Provenance.APPROXIMATE -> "approx"
                        Provenance.MACHINE -> "machine"
                    },
                    style = MaterialTheme.typography.labelSmall.copy(
                        fontSize = 8.5.sp,
                        color = if (row.isMachine) Color(0xFFB45309) else Color(0xFF94A3B8),
                    ),
                )
            }
        }

        Spacer(Modifier.weight(1f))

        if (sheet.needsReviewCount > 0) {
            // §4.5 does not stop applying because the medium is a page rather than a voice.
            Text(
                "\u26A0 ${sheet.needsReviewCount} of ${sheet.rows.size} lines are machine " +
                    "translations. No speaker has checked them.",
                style = MaterialTheme.typography.labelSmall.copy(
                    fontSize = 9.5.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = Color(0xFFB45309),
                ),
            )
        }
    }
}
